# Generated by Django 5.1.2 on 2024-10-16 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.university'),
        ),
    ]
