# Generated by Django 5.1.2 on 2024-10-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='subtitle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
