# Generated by Django 5.1.2 on 2024-10-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_material_subtitle_material_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('past_paper', 'Past Paper'), ('notes', 'Notes'), ('research', 'Research'), ('timetable', 'Timetable'), ('quiz', 'Quiz')], max_length=50),
        ),
    ]
