# Generated by Django 5.1.2 on 2024-10-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_material_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_breaking_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('past_paper', 'Past Paper'), ('notes', 'Notes'), ('research', 'Research'), ('timetable', 'Timetable'), ('report', 'Report')], max_length=50),
        ),
    ]
