# Generated by Django 5.1.2 on 2024-10-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blog_is_breaking_news_alter_material_material_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='event',
            name='course',
        ),
    ]
