# Generated by Django 5.1.2 on 2024-10-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_event_description_alter_event_date_alter_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
