# Generated by Django 5.1.2 on 2024-11-02 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_message_receiver_message_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.university'),
        ),
    ]
