# Generated by Django 5.1.2 on 2024-11-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_requestevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestevent',
            old_name='image',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='requestevent',
            name='is_breaking_news',
        ),
        migrations.RemoveField(
            model_name='requestevent',
            name='university',
        ),
        migrations.AddField(
            model_name='requestevent',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='phone_number',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
