# Generated by Django 5.1.2 on 2024-11-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_image_requestevent_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestevent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
