# Generated by Django 5.1.2 on 2024-12-03 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_userprofile_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('mobile', 'Mobile'), ('sport', 'Sport'), ('fashion', 'Fashion'), ('lifestyle', 'Lifestyle'), ('computer', 'Computer'), ('elecronics', 'Electronics'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255, null=True)),
                ('feature1', models.CharField(blank=True, max_length=255, null=True)),
                ('feature2', models.CharField(blank=True, max_length=255, null=True)),
                ('feature3', models.CharField(blank=True, max_length=255, null=True)),
                ('feature4', models.CharField(blank=True, max_length=255, null=True)),
                ('waranty', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='e-commerce/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
