# Generated by Django 5.1.2 on 2024-12-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_image_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='waranty',
            new_name='warranty',
        ),
    ]
