# Generated by Django 5.1.2 on 2024-12-09 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_message_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
