# Generated by Django 5.1.2 on 2025-01-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('sport', 'Sport'), ('fashion', 'Fashion'), ('lifestyle', 'Lifestyle'), ('computer', 'Computer'), ('electronics', 'Electronics'), ('other', 'Other')], max_length=50),
        ),
    ]
